USE cheetah;

-- Make sure Billing.bill_id auto-generates new IDs
ALTER TABLE Billing
  MODIFY bill_id INT NOT NULL AUTO_INCREMENT;

-- Insert a new bill WITHOUT specifying bill_id
INSERT INTO Billing (customer_id, staff_id, bill_date)
VALUES (11011, 51012, CURDATE());

-- Show the ID that was generated by the last insert
SELECT LAST_INSERT_ID() AS new_bill_id;

-- Prove the row exists
SELECT * FROM Billing WHERE bill_id = LAST_INSERT_ID();
